// src/components/Navbar.svelte
<script lang="ts">
	import { subscribeNumOfItemsInCart } from '$lib/store/cartStore';

	let numOfItemsInCart: number;
	subscribeNumOfItemsInCart((numItemsCart) => {
		numOfItemsInCart = numItemsCart;
	});
</script>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">Amazon clone</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon" />
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="#">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li>
				<li class="nav-item dropdown">
					<a
						class="nav-link dropdown-toggle"
						href="#"
						id="navbarDropdown"
						role="button"
						data-bs-toggle="dropdown"
						aria-expanded="false"
					>
						Dropdown
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="#">Action</a></li>
						<li><a class="dropdown-item" href="#">Another action</a></li>
						<li><hr class="dropdown-divider" /></li>
						<li><a class="dropdown-item" href="#">Something else here</a></li>
					</ul>
				</li>
				<li class="nav-item">
					<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
				</li>
			</ul>
			<a class="nav-link" href="/cart">cart: {numOfItemsInCart}</a>
			<form class="d-flex">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>
		</div>
	</div>
</nav>

// components/nav/Navbar.tsx
import Link from 'next/link';
import { useAppDispatch, useAppSelector } from '../../app/hooks';
import { getAuthUser, setAuthUser } from '../../store/authSlice';
import { getNumOfItemsInCart } from '../../store/cartSlice';
import { supabase } from '$lib/supabase';
import Search from '../misc/Search';

const Navbar: React.FC = () => {
	const dispatch = useAppDispatch();

	const authUser = useAppSelector(getAuthUser);
	const numOfItemsInCart = useAppSelector(getNumOfItemsInCart);

	supabase.auth.onAuthStateChange(() =>
		dispatch(setAuthUser(supabase.auth.user()))
	);

	const signOut = () => {
		supabase.auth.signOut();
	};

	return (
		<nav className="navbar navbar-expand-lg navbar-light bg-light">
			<div className="container-fluid">
				<Link href="/">
					<a className="navbar-brand">Amazon clone</a>
				</Link>
				<button
					className="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarSupportedContent"
					aria-controls="navbarSupportedContent"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span className="navbar-toggler-icon" />
				</button>
				<div className="collapse navbar-collapse" id="navbarSupportedContent">
					<ul className="navbar-nav me-auto mb-2 mb-lg-0">
						{authUser ? (
							<>
								<li className="nav-item">
									<button onClick={signOut} className="btn nav-link">
										Sign out
									</button>
								</li>
								<li className="nav-item">
									<Link href="/orders">
										<a className="nav-link">My orders</a>
									</Link>
								</li>
							</>
						) : (
							<>
								<li className="nav-item">
									<Link href="/login">
										<a className="nav-link">Login</a>
									</Link>
								</li>
								<li className="nav-item">
									<Link href="/signup">
										<a className="nav-link">Sign up</a>
									</Link>
								</li>
							</>
						)}
					</ul>
					{authUser && (
						<Link href="/cart">
							<a className="nav-link">cart: {numOfItemsInCart}</a>
						</Link>
					)}
					<Search />
				</div>
			</div>
		</nav>
	);
};

export default Navbar;
